version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ApprovalUtilities
    versions:
    - 5.4.5
    - 5.4.6
  - dependency-name: ApprovalTests
    versions:
    - 5.4.5
    - 5.4.6
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: Microsoft.Build.Tasks.Core
    versions:
    - 16.8.0
  - dependency-name: Microsoft.Build.Framework
    versions:
    - 16.8.0
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
